version: '3'

tasks:
  format:
    cmds:
      - task: go_files
        vars: { COMMAND: 'gofmt -w  {} +'}
      - task: go_files
        vars: { COMMAND: 'goimports -w  {} +'}

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - revive
        -config revive.toml
        -formatter friendly
        -exclude ./mock
        ./...

  precommit:
    desc: "Run all precommit checks"
    cmds:
      - task: format
      - task: test
      - task: lint

## INTERNAL COMMANDS

  go_files:
    desc: "Return all .go files and run .COMMAND on them"
    internal: true
    cmds:
     - find .
        -name "*.go"
        -not -path ./mock
        -exec {{.COMMAND}};
